sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx7fed18c49c76f14a
    secret: 20c3d989970e70f76a327568166011e8